pull handle only
andrew-shackelford/Harvard_Twitter_Research_2018 pull request #18
Opened 2018-10-20 23:54 UTC by hljames

Pull the handle only, rather than the whole user object

2018-10-21 20:21 UTC, emmaling27 requested changes
removing commented out code is probably best so people don't get confused

2018-10-21 20:21 UTC, emmaling27 commented on twitter_user_handles.py
> +    # with open(out_dir + "/" + out_file + '.json', 'a') as outFile: # entire user object
remove this commented out line

2018-10-21 20:21 UTC, emmaling27 commented on twitter_user_handles.py
> +                    # json.dump(user._json, outFile) # entire user object
also remove this commented out line

2018-11-02 14:19 UTC, hljames commented
All set!

2018-11-05 14:55 UTC, jimwaldo approved these changes

2018-11-06 05:00 UTC, emmaling27 approved these changes

2018-11-06 05:00 UTC, merged